"""
The script expects a file generated by
bed coverage -hist
The fraction of each mRNA covered with
depth > X is calculated, and mRNAs with
fraction > Y are called present.
The output looks like:
Gene	sample_name
gene1	1
gene2	0
gene3	1
"""

from __future__ import print_function
import sys

in_bed_cov = sys.argv[1]
min_depth = int(sys.argv[2])
min_frac = float(sys.argv[3])
sample_name = sys.argv[4]

cov_dict = {}
with open(in_bed_cov) as f:
  for line in f:
    fields = line.strip().split("\t")
    if fields[0] == "all":
      continue
    name = fields[3]
    if name not in cov_dict:
      cov_dict[name] = 0
    depth = int(fields[4])
    if depth < min_depth:
      continue
    frac = float(fields[7])
    cov_dict[name] += frac

print("Gene\t%s" % sample_name)
for g in cov_dict:
  if cov_dict[g] < min_frac:
    pres = "0"
  else:
    pres = "1"
  print("%s\t%s" %(g,pres))
