cp /groups/itay_mayrose/nosnap/liorglic/Projects/PGCM/python/PGC_de_novo/break_OrthoFinder_clusters.py de_novo/
cp /groups/itay_mayrose/nosnap/liorglic/Projects/PGCM/python/PGC_de_novo/create_pan_proteins_fasta.py de_novo/
cp /groups/itay_mayrose/nosnap/liorglic/Projects/PGCM/python/PGC_de_novo/create_PAV_matrix.py de_novo/
cp /groups/itay_mayrose/nosnap/liorglic/Projects/PGCM/python/PGC_map_to_pan/create_PAV_matrix.py map_to_pan/
cp /groups/itay_mayrose/nosnap/liorglic/Projects/PGCM/python/PGC_de_novo/improve_GAWN_liftover.py de_novo/
cp /groups/itay_mayrose/nosnap/liorglic/Projects/PGCM/python/PGC_de_novo/ragoo_ordering_to_bed.py de_novo/
cp /groups/itay_mayrose/nosnap/liorglic/Projects/PGCM/python/filter_gff_by_id_list.py util/
cp /groups/itay_mayrose/nosnap/liorglic/Projects/PGCM/python/split_gff_by_source.py util/
cp /groups/itay_mayrose/nosnap/liorglic/Projects/PGCM/python/transform_gff_coordinates.py util/
cp /groups/itay_mayrose/nosnap/liorglic/Projects/PGCM/python/PGC_map_to_pan/detect_gene_PAV_from_bed_cov.py map_to_pan/
cp /groups/itay_mayrose/nosnap/liorglic/Projects/PGCM/python/PGC_map_to_pan/iterative_map_to_pan.py map_to_pan/
cp /groups/itay_mayrose/nosnap/liorglic/Projects/PGCM/python/custom_sort_bed.py util/
cp /groups/itay_mayrose/nosnap/liorglic/Projects/PGCM/python/ena-fast-download.py util/
cp /groups/itay_mayrose/nosnap/liorglic/Projects/PGCM/python/extract_transcripts_and_proteins_from_gff.py util/
cp /groups/itay_mayrose/nosnap/liorglic/Projects/PGCM/python/filter_by_aed.py util/
cp /groups/itay_mayrose/nosnap/liorglic/Projects/PGCM/python/filter_contigs.py util/
cp /groups/itay_mayrose/nosnap/liorglic/Projects/PGCM/python/filter_fasta_by_gff.py util/
cp /groups/itay_mayrose/nosnap/liorglic/Projects/PGCM/python/pbs_qsub_snakemake_wrapper.py util/
cp /groups/itay_mayrose/nosnap/liorglic/Projects/PGCM/python/prevent_duplicate_names.py util/
cp /groups/itay_mayrose/nosnap/liorglic/Projects/PGCM/python/remove_alt_splicing_from_gff.py util/
cp /groups/itay_mayrose/nosnap/liorglic/Projects/PGCM/python/simplify_gff_id.py util/

cp /groups/itay_mayrose/nosnap/liorglic/Projects/PGCM/python/pan_genome_stats/collect_stats.py pan_genome_report/
cp /groups/itay_mayrose/nosnap/liorglic/Projects/PGCM/python/pan_genome_stats/calc_stepwise_stats.py pan_genome_report/
cp /groups/itay_mayrose/nosnap/liorglic/Projects/PGCM/python/pan_genome_stats/report_template.ipynb pan_genome_report/

cp /groups/itay_mayrose/nosnap/liorglic/Projects/PGCM/python/jobscript.sh util/

cp /groups/itay_mayrose/nosnap/liorglic/Projects/PGCM/python/annotation_pipeline/annotation_qa.py genome_annotation/
cp /groups/itay_mayrose/nosnap/liorglic/Projects/PGCM/python/annotation_pipeline/edit_maker_conf.py genome_annotation/
cp /groups/itay_mayrose/nosnap/liorglic/Projects/PGCM/python/annotation_pipeline/run_MAKER_in_chunks.snakefile genome_annotation/
cp -r /groups/itay_mayrose/nosnap/liorglic/Projects/PGCM/python/annotation_pipeline/annotation_templates/ genome_annotation/

cp /groups/itay_mayrose/nosnap/liorglic/Projects/PGCM/python/PGC_de_novo/conda_env/break_orthogroups.yml conda_env/
cp /groups/itay_mayrose/nosnap/liorglic/Projects/PGCM/python/PGC_de_novo/conda_env/break_orthogroups.yml conda_env/
cp /groups/itay_mayrose/nosnap/liorglic/Projects/PGCM/python/PGC_de_novo/conda_env/busco.yml conda_env/
cp /groups/itay_mayrose/nosnap/liorglic/Projects/PGCM/python/PGC_de_novo/conda_env/busco.yml conda_env/
cp /groups/itay_mayrose/nosnap/liorglic/Projects/PGCM/python/PGC_de_novo/conda_env/faSplit.yml conda_env/
cp /groups/itay_mayrose/nosnap/liorglic/Projects/PGCM/python/PGC_de_novo/conda_env/flash.yml conda_env/
cp /groups/itay_mayrose/nosnap/liorglic/Projects/PGCM/python/PGC_de_novo/conda_env/GAWN.yml conda_env/
cp /groups/itay_mayrose/nosnap/liorglic/Projects/PGCM/python/PGC_de_novo/conda_env/GAWN.yml conda_env/
cp /groups/itay_mayrose/nosnap/liorglic/Projects/PGCM/python/PGC_de_novo/conda_env/GAWN.yml conda_env/
cp /groups/itay_mayrose/nosnap/liorglic/Projects/PGCM/python/PGC_de_novo/conda_env/gffutils.yml conda_env/
cp /groups/itay_mayrose/nosnap/liorglic/Projects/PGCM/python/PGC_de_novo/conda_env/gffutils.yml conda_env/
cp /groups/itay_mayrose/nosnap/liorglic/Projects/PGCM/python/PGC_de_novo/conda_env/gffutils.yml conda_env/
cp /groups/itay_mayrose/nosnap/liorglic/Projects/PGCM/python/PGC_de_novo/conda_env/gffutils.yml conda_env/
cp /groups/itay_mayrose/nosnap/liorglic/Projects/PGCM/python/PGC_de_novo/conda_env/gffutils.yml conda_env/
cp /groups/itay_mayrose/nosnap/liorglic/Projects/PGCM/python/PGC_de_novo/conda_env/gffutils.yml conda_env/
cp /groups/itay_mayrose/nosnap/liorglic/Projects/PGCM/python/PGC_de_novo/conda_env/gffutils.yml conda_env/
cp /groups/itay_mayrose/nosnap/liorglic/Projects/PGCM/python/PGC_de_novo/conda_env/gffutils.yml conda_env/
cp /groups/itay_mayrose/nosnap/liorglic/Projects/PGCM/python/PGC_de_novo/conda_env/gffutils.yml conda_env/
cp /groups/itay_mayrose/nosnap/liorglic/Projects/PGCM/python/PGC_de_novo/conda_env/gffutils.yml conda_env/
cp /groups/itay_mayrose/nosnap/liorglic/Projects/PGCM/python/PGC_de_novo/conda_env/index_gff.yml conda_env/
cp /groups/itay_mayrose/nosnap/liorglic/Projects/PGCM/python/PGC_de_novo/conda_env/index_gff.yml conda_env/
cp /groups/itay_mayrose/nosnap/liorglic/Projects/PGCM/python/PGC_de_novo/conda_env/jupyter.yml conda_env/
cp /groups/itay_mayrose/nosnap/liorglic/Projects/PGCM/python/PGC_de_novo/conda_env/jupyter.yml conda_env/
cp /groups/itay_mayrose/nosnap/liorglic/Projects/PGCM/python/PGC_de_novo/conda_env/jupyter.yml conda_env/
cp /groups/itay_mayrose/nosnap/liorglic/Projects/PGCM/python/PGC_de_novo/conda_env/orthofinder2.yml conda_env/
cp /groups/itay_mayrose/nosnap/liorglic/Projects/PGCM/python/PGC_de_novo/conda_env/quast.yml conda_env/
cp /groups/itay_mayrose/nosnap/liorglic/Projects/PGCM/python/PGC_de_novo/conda_env/RaGOO.yml conda_env/
cp /groups/itay_mayrose/nosnap/liorglic/Projects/PGCM/python/PGC_de_novo/conda_env/samtools.yml conda_env/
cp /groups/itay_mayrose/nosnap/liorglic/Projects/PGCM/python/PGC_de_novo/conda_env/snakemake.yml conda_env/
cp /groups/itay_mayrose/nosnap/liorglic/Projects/PGCM/python/PGC_de_novo/conda_env/snakemake.yml conda_env/
cp /groups/itay_mayrose/nosnap/liorglic/Projects/PGCM/python/PGC_de_novo/conda_env/snakemake.yml conda_env/
cp /groups/itay_mayrose/nosnap/liorglic/Projects/PGCM/python/PGC_de_novo/conda_env/snakemake.yml conda_env/
cp /groups/itay_mayrose/nosnap/liorglic/Projects/PGCM/python/PGC_de_novo/conda_env/spades.yml conda_env/
cp /groups/itay_mayrose/nosnap/liorglic/Projects/PGCM/python/PGC_de_novo/conda_env/TransDecoder.yml conda_env/
cp /groups/itay_mayrose/nosnap/liorglic/Projects/PGCM/python/PGC_de_novo/conda_env/trimmomatic.yml conda_env/
cp /groups/itay_mayrose/nosnap/liorglic/Projects/PGCM/python/PGC_map_to_pan/conda_env/bedtools.yml conda_env/
cp /groups/itay_mayrose/nosnap/liorglic/Projects/PGCM/python/PGC_map_to_pan/conda_env/bedtools.yml conda_env/
cp /groups/itay_mayrose/nosnap/liorglic/Projects/PGCM/python/PGC_map_to_pan/conda_env/busco.yml conda_env/
cp /groups/itay_mayrose/nosnap/liorglic/Projects/PGCM/python/PGC_map_to_pan/conda_env/bwa.yml conda_env/
cp /groups/itay_mayrose/nosnap/liorglic/Projects/PGCM/python/PGC_map_to_pan/conda_env/bwa.yml conda_env/
cp /groups/itay_mayrose/nosnap/liorglic/Projects/PGCM/python/PGC_map_to_pan/conda_env/cd-hit.yml conda_env/
cp /groups/itay_mayrose/nosnap/liorglic/Projects/PGCM/python/PGC_map_to_pan/conda_env/faSplit.yml conda_env/
cp /groups/itay_mayrose/nosnap/liorglic/Projects/PGCM/python/PGC_map_to_pan/conda_env/flash.yml conda_env/
cp /groups/itay_mayrose/nosnap/liorglic/Projects/PGCM/python/PGC_map_to_pan/conda_env/gffutils.yml conda_env/
cp /groups/itay_mayrose/nosnap/liorglic/Projects/PGCM/python/PGC_map_to_pan/conda_env/gffutils.yml conda_env/
cp /groups/itay_mayrose/nosnap/liorglic/Projects/PGCM/python/PGC_map_to_pan/conda_env/iterative_map_to_pan.yml conda_env/
cp /groups/itay_mayrose/nosnap/liorglic/Projects/PGCM/python/PGC_map_to_pan/conda_env/iterative_map_to_pan.yml conda_env/
cp /groups/itay_mayrose/nosnap/liorglic/Projects/PGCM/python/PGC_map_to_pan/conda_env/jupyter.yml conda_env/
cp /groups/itay_mayrose/nosnap/liorglic/Projects/PGCM/python/PGC_map_to_pan/conda_env/jupyter.yml conda_env/
cp /groups/itay_mayrose/nosnap/liorglic/Projects/PGCM/python/PGC_map_to_pan/conda_env/minimap2.yml conda_env/
cp /groups/itay_mayrose/nosnap/liorglic/Projects/PGCM/python/PGC_map_to_pan/conda_env/pandas.yml conda_env/
cp /groups/itay_mayrose/nosnap/liorglic/Projects/PGCM/python/PGC_map_to_pan/conda_env/pandas.yml conda_env/
cp /groups/itay_mayrose/nosnap/liorglic/Projects/PGCM/python/PGC_map_to_pan/conda_env/quast.yml conda_env/
cp /groups/itay_mayrose/nosnap/liorglic/Projects/PGCM/python/PGC_map_to_pan/conda_env/samtools.yml conda_env/
cp /groups/itay_mayrose/nosnap/liorglic/Projects/PGCM/python/PGC_map_to_pan/conda_env/samtools.yml conda_env/
cp /groups/itay_mayrose/nosnap/liorglic/Projects/PGCM/python/PGC_map_to_pan/conda_env/samtools.yml conda_env/
cp /groups/itay_mayrose/nosnap/liorglic/Projects/PGCM/python/PGC_map_to_pan/conda_env/samtools.yml conda_env/
cp /groups/itay_mayrose/nosnap/liorglic/Projects/PGCM/python/PGC_map_to_pan/conda_env/snakemake.yml conda_env/
cp /groups/itay_mayrose/nosnap/liorglic/Projects/PGCM/python/PGC_map_to_pan/conda_env/snakemake.yml conda_env/
cp /groups/itay_mayrose/nosnap/liorglic/Projects/PGCM/python/PGC_map_to_pan/conda_env/snakemake.yml conda_env/
cp /groups/itay_mayrose/nosnap/liorglic/Projects/PGCM/python/PGC_map_to_pan/conda_env/snakemake.yml conda_env/
cp /groups/itay_mayrose/nosnap/liorglic/Projects/PGCM/python/PGC_map_to_pan/conda_env/spades.yml conda_env/
cp /groups/itay_mayrose/nosnap/liorglic/Projects/PGCM/python/PGC_map_to_pan/conda_env/trimmomatic.yml conda_env/
